import type { Config } from "tailwindcss";

const config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  safelist: [
    // Classes de gradiente para o componente ProgressPizza
    'bg-gradient-to-r',
    'from-red-500',
    'to-red-600',
    'from-orange-500',
    'to-orange-600',
    'from-yellow-500',
    'to-yellow-600',
    'from-green-500',
    'to-green-600',
    'from-blue-500',
    'to-blue-600',
    'from-blue-600',
    'to-blue-700',
    // Classes de texto com gradiente
    'bg-clip-text',
    'text-transparent',
    // Classes para cards e layout
    'line-clamp-3',
    'truncate',
    'group',
    'group-hover',
    'hover:shadow-md',
    'shadow-sm',
    'overflow-hidden',
    'bg-white/20',
    'hover:bg-white/20',
    // Classes de grid responsivo
    'grid-cols-1',
    'sm:grid-cols-2',
    'lg:grid-cols-3',
    'lg:col-span-1',
    'lg:col-span-2',
    // Classes de flex responsivo
    'flex-col',
    'sm:flex-row',
    // Classes de texto responsivo
    'text-xl',
    'sm:text-2xl',
    // Classes de padding responsivo
    'px-4',
    'sm:px-6',
    // Classes de margin responsivo
    'sm:ml-auto',
    // Classes de display responsivo
    'hidden',
    'md:inline',
    'md:hidden',
    // Classes de overflow
    'overflow-x-auto',
    'overflow-y-auto',
    // Classes de truncate
    'truncate',
    // Classes de min-width
    'min-w-0',
    // Classes de width
    'w-fit',
    'w-full',
    'w-5',
    'w-6',
    'w-8',
    // Classes de altura
    'h-2',
    'h-5',
    'h-6',
    'h-8',
    'h-10',
    'h-1.5',
    'h-32',
    'h-24',
    // Classes de padding
    'p-0',
    'p-1',
    'p-1.5',
    'p-2',
    'p-3',
    'p-4',
    'py-2',
    // Classes de margin
    'mb-1',
    'mb-2',
    'mb-4',
    // Classes de gap
    'gap-2',
    'gap-3',
    'gap-4',
    'gap-6',
    'gap-1.5',
    // Classes de spacing
    'space-y-1',
    // Classes para pesquisa
    'pl-10',
    'pr-4',
    'py-2',
    'pl-3',
    'pr-3',
    'focus:border-blue-500',
    'focus:ring-blue-500',
    'hover:text-gray-600',
    'text-gray-400',
    'text-gray-600',
    'text-blue-600',
    'text-blue-700',
    'text-yellow-600',
    'bg-yellow-100',
    'bg-orange-100',
    'from-yellow-100',
    'to-orange-100',
    'border-blue-200',
    'hover:border-blue-300',
    'hover:text-blue-700',
    // Classes para tabs responsivas
    'flex-1',
    'space-y-2',
    'space-y-4',
    'gap-1.5',
    // Classes de border
    'border-blue-100',
    'border-blue-200',
    'border-blue-300',
    'border-gray-200',
    'rounded-full',
    'colSpan',
    'divide-y',
    'divide-gray-200',
    // Classes de background
    'bg-gray-50',
    'bg-gray-50/50',
    'bg-white',
    'bg-blue-100',
    'bg-purple-100',
    'bg-red-50',
    'from-blue-50',
    'from-blue-100',
    'to-purple-50',
    'to-purple-100',
    // Classes de texto
    'text-blue-100',
    'text-blue-600',
    'text-blue-700',
    'text-blue-800',
    'text-blue-900',
    'text-purple-600',
    'text-gray-500',
    'text-gray-600',
    'text-gray-700',
    'text-gray-800',
    'text-gray-900',
    'text-white',
    'text-red-600',
    'text-red-900',
    'text-blue-700',
    'text-blue-800',
    'text-gray-700',
    // Classes de fonte
    'font-bold',
    'font-semibold',
    'font-medium',
    'font-normal',
    // Classes de tamanho de texto
    'text-lg',
    'text-sm',
    'text-xs',
    'text-2xl',
    'w-1/3',
    // Classes de margin top
    'mt-0.5',
    'mt-1.5',
    'mt-2',
    'mb-1',
    'mb-2',
    'mb-3',
    // Classes de flex
    'flex-col',
    'flex-row',
    'flex-wrap',
    'items-center',
    'items-start',
    'justify-center',
    'justify-between',
    'flex-1',
    'min-w-0',
    'py-1',
    'inline-flex',
    'min-h-[80px]',
    'min-h-[600px]',
    'min-h-[400px]',
    // Classes de grid
    'grid-cols-2',
    'grid-cols-3',
    // Classes de transição
    'transition-all',
    'duration-200',
    'duration-500',
    // Classes de hover
    'hover:shadow-md',
    'hover:bg-white/20',
    'hover:bg-red-50',
    'hover:text-red-900',
    'hover:from-blue-100',
    'hover:from-blue-200',
    'hover:to-purple-100',
    'hover:to-purple-200',
    // Classes de max height
    'max-h-20',
    'max-h-24',
    'max-h-32',
    'max-h-[400px]',
    'max-h-[500px]',
    'overflow-auto',
    'min-h-0',
    'flex-1',
    'h-full',
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        card: {
          DEFAULT: "var(--card)",
          foreground: "var(--card-foreground)",
        },
        popover: {
          DEFAULT: "var(--popover)",
          foreground: "var(--popover-foreground)",
        },
        primary: {
          DEFAULT: "var(--primary)",
          foreground: "var(--primary-foreground)",
        },
        secondary: {
          DEFAULT: "var(--secondary)",
          foreground: "var(--secondary-foreground)",
        },
        muted: {
          DEFAULT: "var(--muted)",
          foreground: "var(--muted-foreground)",
        },
        accent: {
          DEFAULT: "var(--accent)",
          foreground: "var(--accent-foreground)",
        },
        destructive: {
          DEFAULT: "var(--destructive)",
          foreground: "var(--destructive-foreground)",
        },
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        chart: {
          "1": "var(--chart-1)",
          "2": "var(--chart-2)",
          "3": "var(--chart-3)",
          "4": "var(--chart-4)",
          "5": "var(--chart-5)",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [],
};

export default config; 